[theme]
primaryColor = "#0b79bf"
backgroundColor = "#f2f4f7"
secondaryBackgroundColor = "#e8f1f8"
textColor = "#1f3349"
font = "sans serif"

[server]
headless = true
enableCORS = false

[browser]
gatherUsageStats = false
