[theme]
primaryColor = "#0c5ca8"
backgroundColor = "#f8fcff"
secondaryBackgroundColor = "#eaf5fc"
textColor = "#12324f"
font = "sans serif"

[server]
headless = true
enableCORS = false

[browser]
gatherUsageStats = false
